// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrintManagement.Data;

namespace PrintManagement.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200921162942_Mysql")]
    partial class Mysql
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PrintManagement.Models.ContadorDeImpressao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataLeitura")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("IdDepartamento")
                        .HasColumnType("bigint");

                    b.Property<long>("IdEmpressora")
                        .HasColumnType("bigint");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdDepartamento");

                    b.HasIndex("IdEmpressora");

                    b.ToTable("ContadorDeImpressao");
                });

            modelBuilder.Entity("PrintManagement.Models.ContratoDeImpressora", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Franquia")
                        .HasColumnType("int");

                    b.Property<long>("Idfornecedor")
                        .HasColumnType("bigint");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<float>("ValorContrato")
                        .HasColumnType("float");

                    b.Property<float>("ValorExcedente")
                        .HasColumnType("float");

                    b.Property<int>("Vigencia")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Idfornecedor")
                        .IsUnique();

                    b.ToTable("ContratoDeImpressora");
                });

            modelBuilder.Entity("PrintManagement.Models.Departamento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Departamento");
                });

            modelBuilder.Entity("PrintManagement.Models.Filial", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("DDD")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Filial");
                });

            modelBuilder.Entity("PrintManagement.Models.Fornecedor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Contato")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Site")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Fornecedor");
                });

            modelBuilder.Entity("PrintManagement.Models.Impressora", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("IdContratoDeImpressora")
                        .HasColumnType("bigint");

                    b.Property<long>("IdDepartamento")
                        .HasColumnType("bigint");

                    b.Property<long>("IdFilial")
                        .HasColumnType("bigint");

                    b.Property<long>("IdModelo")
                        .HasColumnType("bigint");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Serial")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<long?>("derpartamentoId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IdContratoDeImpressora");

                    b.HasIndex("IdFilial");

                    b.HasIndex("IdModelo");

                    b.HasIndex("derpartamentoId");

                    b.ToTable("Impressora");
                });

            modelBuilder.Entity("PrintManagement.Models.LogsImpressao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("LogsImpressao");
                });

            modelBuilder.Entity("PrintManagement.Models.Modelo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Modelo");
                });

            modelBuilder.Entity("PrintManagement.Models.ContadorDeImpressao", b =>
                {
                    b.HasOne("PrintManagement.Models.Departamento", "Derpartamento")
                        .WithMany("ContadorDeImpressaos")
                        .HasForeignKey("IdDepartamento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrintManagement.Models.Impressora", "Impressora")
                        .WithMany("ContadorDeImpressaos")
                        .HasForeignKey("IdEmpressora")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PrintManagement.Models.ContratoDeImpressora", b =>
                {
                    b.HasOne("PrintManagement.Models.Fornecedor", "Fornecedor")
                        .WithOne("ContratoDeImpressora")
                        .HasForeignKey("PrintManagement.Models.ContratoDeImpressora", "Idfornecedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PrintManagement.Models.Impressora", b =>
                {
                    b.HasOne("PrintManagement.Models.ContratoDeImpressora", "ContratoDeImpressora")
                        .WithMany("Impressoras")
                        .HasForeignKey("IdContratoDeImpressora")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrintManagement.Models.Filial", "Filial")
                        .WithMany("Impressoras")
                        .HasForeignKey("IdFilial")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrintManagement.Models.Modelo", "Modelo")
                        .WithMany("Impressoras")
                        .HasForeignKey("IdModelo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrintManagement.Models.Departamento", "derpartamento")
                        .WithMany("Impressoras")
                        .HasForeignKey("derpartamentoId");
                });
#pragma warning restore 612, 618
        }
    }
}
